import { StyleSheet } from "react-native";

const card_style = {
  backgroundColor: "white",
  elevation: 5,
  shadowColor: "#000",
  paddingVertical: 8,
  paddingHorizontal: 16,
  borderRadius: 8,
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.75,
  shadowRadius: 4,
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  map: {
    flex: 1,
    width: "100%",
  },
  route_card: {
    ...card_style,
    padding: 8,
    maxHeight: 200,
    position: "absolute",
    top: "0%",
    left: "2%",
    right: "2%",
    flex: 1,
    justifyContent: "center",
    alignContent: "center",
  },
  route_card_title: {
    fontWeight: "bold",
    fontSize: 18,
    fontFamily: "Inter",
  },
  truck_map_card: {
    // position: "absolute",
    backgroundColor: "white",
    elevation: 5,
    shadowColor: "#000",
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.75,
    shadowRadius: 4,
    maxHeight: 200,
    position: "absolute",
    bottom: "5%",
    left: "2%",
    right: "2%",
    flexDirection: "row",
    flex: 1,
    marginHorizontal: 18,
    gap: 32,
    alignItems: "center",
    justifyContent: "space-between",
  },
  menu_card: {
    backgroundColor: "white",
    elevation: 5,
    shadowColor: "#000",
    padding: 12,
    borderRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.75,
    shadowRadius: 4,
    borderColor: "black",
    borderWidth: 1,
  },
  menu_card_inverted: {
    backgroundColor: "black",
    color: "white",
    // borderColor: "white",
  },
  menu_card_text: {
    fontSize: 20,
    textAlign: "center",
    fontFamily: "Oswald",
    // fontWeight: "bold",
  },
  menu_card_text_inverted: {
    fontSize: 20,
    textAlign: "center",
    color: "white",
    fontFamily: "Josefin Sans",
  },
  backbutton: {
    position: "absolute",
    backgroundColor: "white",
    borderRadius: 100,
    paddingVertical: 8,
    paddingHorizontal: 12,
    top: "1%",
    left: "2%",
  },
  route_helper_text: {
    color: "gray",
    display: "flex",
    fontSize: 12,
    flex: 1,
    flexDirection: "row",
    position: "relative",
    top: "1%",
  },
  spaced_out_container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    gap: 48,
  },
  heading1: {
    fontSize: 40,
    textAlign: "center",
    fontWeight: "800",
    fontFamily: "Inter",
  },
  heading2: {
    fontSize: 20,
    textAlign: "center",
    fontWeight: "800",
    fontFamily: "Oswald",
  },
});
