import { StyleSheet } from "react-native";

const card_style = {
  backgroundColor: "white",
  elevation: 5,
  shadowColor: "#000",
  paddingVertical: 8,
  paddingHorizontal: 16,
  borderRadius: 8,
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.75,
  shadowRadius: 4,
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  map: {
    flex: 1,
    width: "100%",
  },
  route_card: {
    ...card_style,
    maxHeight: 200,
    position: "absolute",
    top: "5%",
    left: "2%",
    right: "2%",
  },
  route_card_title: {
    fontWeight: "bold",
    fontSize: 18,
    fontFamily: "Inter",
  },
  truck_map_card: {
    // position: "absolute",
    backgroundColor: "white",
    elevation: 5,
    shadowColor: "#000",
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.75,
    shadowRadius: 4,
    maxHeight: 200,
    position: "absolute",
    bottom: "5%",
    left: "2%",
    right: "2%",
    flexDirection: "row",
    flex: 1,
    marginHorizontal: 18,
    gap: 32,
    alignItems: "center",
    justifyContent: "space-between",
  },
  menu_card: {
    ...card_style,
    borderColor: "black",
    borderWidth: 1,
  },
  backbutton: {
    position: "absolute",
    backgroundColor: "white",
    borderRadius: 100,
    paddingVertical: 8,
    paddingHorizontal: 12,
    top: "1%",
    left: "2%",
  },
});
